
# Using the official Python 3.11.9 image as the base image
FROM debian:bullseye-slim

# Set environment variables to prevent Python from writing .pyc files and buffering output
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# Downloading the system's dependencies
RUN apt-get update && apt-get install -y \
    python3 python3-pip \
    procps \
    wget \
    curl \
    docker.io \
    postgresql-client  \
    libpq-dev \
    && rm -rf /var/lib/apt/lists/*

RUN ln -s /usr/bin/python3 /usr/bin/python

# Copying the application files
COPY . /app

# Installing Python dependencies
RUN pip install --upgrade pip
COPY requirements_airflow.txt .
RUN pip install -r requirements_airflow.txt

# Set working directory
WORKDIR /app

COPY entrypoint.sh /app/entrypoint.sh
RUN chmod +x /app/entrypoint.sh

# Expose Airflow webserver port
EXPOSE 8080

ENTRYPOINT ["/app/entrypoint.sh"]